######################################################################
# Automatically generated by qmake (2.01a) sam. déc. 8 22:48:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test_qt.cpp
